[[install]]
== 安装 Kibana

NOTE: Starting with version 6.0.0, Kibana only supports 64 bit operating systems.
注意：从 6.0.0 版本开始，Kibana 只支持 64 位的系统。

Kibana 提供以下格式的安装包：

[horizontal]
`tar.gz`/`zip`::

'tar.gz'包用来在Linux和Darwin系统下安装，而且也是开始Kibana最简单的一种选择。
+
‘zip’包是唯一支持 Windows 系统的安装包。
+
<<targz>> or <<windows>>

`deb`::

Debian包用来在Debian，Ubuntu，和其他基于Debian的系统下安装，Debian包可以从Elastic 官网或者我们的 Debian 仓库中下载。
+
<<deb>>

`rpm`::

'rpm'包用来在Red Hat，Centos，SLES，OpenSuSe以及其他基于RPM的系统下安装。RPM包可以从Elastic官网或者我们的RPM仓库下载。
+
<<rpm>>

`docker`::

An image is available for running Kibana as a Docker container. It ships
with https://www.elastic.co/products/x-pack[X-Pack] pre-installed and is
available from the Elastic
Docker registry.
+
<<docker>>

IMPORTANT: If your Elasticsearch installation is protected by {xpack-ref}xpack-security.html[X-Pack Security]
see {xpack-ref}kibana.html[Using Kibana with X-Pack Security] for additional setup
instructions.


include::install/targz.asciidoc[]

include::install/deb.asciidoc[]

include::install/rpm.asciidoc[]

include::install/windows.asciidoc[]
