[[install]]
== Installing Kibana
== 安装 Kibana

NOTE: Starting with version 6.0.0, Kibana only supports 64 bit operating systems.
注意：从 6.0.0 版本开始，Kibana 只支持 64 位的系统。

Kibana is provided in the following package formats:
Kibana 提供以下格式的安装包：

[horizontal]
`tar.gz`/`zip`::

The `tar.gz` packages are provided for installation on Linux and Darwin and are
the easiest choice for getting started with Kibana.
+
The `zip` package is the only supported package for Windows.
‘zip’包是唯一支持 Windows 系统的安装包。
+
<<targz>> or <<windows>>

`deb`::

The `deb` package is suitable for Debian, Ubuntu, and other Debian-based
systems.  Debian packages may be downloaded from the Elastic website or from
our Debian repository.
Debian包可以从Elastic 官网或者我们的 Debian 仓库中下载。
+
<<deb>>

`rpm`::

The `rpm` package is suitable for installation on Red Hat, Centos, SLES,
OpenSuSE and other RPM-based systems.  RPMs may be downloaded from the
Elastic website or from our RPM repository.
+
<<rpm>>

`docker`::

An image is available for running Kibana as a Docker container. It ships
with https://www.elastic.co/products/x-pack[X-Pack] pre-installed and is
available from the Elastic
Docker registry.
+
<<docker>>

IMPORTANT: If your Elasticsearch installation is protected by {xpack-ref}xpack-security.html[X-Pack Security]
see {xpack-ref}kibana.html[Using Kibana with X-Pack Security] for additional setup
instructions.


include::install/targz.asciidoc[]

include::install/deb.asciidoc[]

include::install/rpm.asciidoc[]

include::install/windows.asciidoc[]
