[[windows]]
=== 在 Windows 上安装 Kibana

在 Windows 中 ，安装 Kibana 使用 `.zip` 包 。

最新稳定版 Kibana 可以从
link:/downloads/kibana[下载 Kibana] 页获得 。
其他版本可以在
link:/downloads/past-releases[过去的版本页] 中找到 。

[[install-windows]]
==== 下载并安装 `.zip` 包

ifeval::["{release-state}"=="unreleased"]

Version {version} of Kibana has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

下载 Kibana v{version} 的 `.zip` windows 文件: 
https://artifacts.elastic.co/downloads/kibana/kibana-{version}-windows-x86_64.zip

用你最喜欢的解压工具解压下载的 zip 包。这会创建一个文件夹叫
kibana-{version}-windows-x86_64, 也就是我们指的 `$KIBANA_HOME` 。在一个
终端窗口中 ， `CD` 到 `$KIBANA_HOME` 目录 ， 例如 ：


["source","sh",subs="attributes"]
----------------------------
CD c:\kibana-{version}-windows-x86_64
----------------------------

endif::[]

[[windows-running]]
==== 从命令行启动 Kibana

Kibana 可以从命令行启动 ， 如下 ：

[source,sh]
--------------------------------------------
.\bin\kibana
--------------------------------------------

默认情况下 ， Kibana 在前台启动 ，输出 log 到 `STDOUT`,
可以通过 `Ctrl-C` 停止 Kibana 。

[[windows-configuring]]
==== 通过配置文件配置 Kibana

Kibana 默认情况下从 `$KIBANA_HOME/config/kibana.yml`
加载配置文件 。该配置文件的格式在
<<settings>> 中做了说明 。

[[windows-layout]]
==== `.zip` 文件目录

`.zip` 整个包是独立的 。默认情况下 ，所有的文件和目录
都在 `$KIBANA_HOME` -- 解压包时创建的目录 下 。

这是非常方便的 ，因为你不需要创建任何目录来
使用 Kibana ，卸载 Kibana 就是简单地删除
`$KIBANA_HOME` 目录 。然而 ，还是建议修改一下
配置文件和数据目录 ，这样就不会删除
重要数据 。


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| 类型 | 描述 | 默认位置 | 设置
| home
  | Kibana 家目录或  `$KIBANA_HOME`
 d| 解压包时创建的目录
 d|

| bin
  | 二进制脚本，包括  `kibana` 启动 Kibana server
    和 `kibana-plugin` 安装插件
  | $KIBANA_HOME\bin
 d|

| config
  | 配置文件包括 `kibana.yml`
  | $KIBANA_HOME\config
 d|

| data
  | Kibana 和其插件写入磁盘的数据文件位置
  | $KIBANA_HOME\data
 d|

| optimize
  | 编译过的源码。某些管理操作 (如 ，插件安装)
    导致运行时重新编译源码 。
  | $KIBANA_HOME\optimize
 d|

| plugins
  | 插件文件位置 。每一个插件都一个单独的二级目录 。
  | $KIBANA_HOME\plugins
 d|

|=======================================================================
